name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
permissions: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: cat .github/super-linter.env >> "$GITHUB_ENV"
      - uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - run: make versions
    - run: make test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: build/
    - name: Validate the changelog
      uses: ./
      id: clq-validate
      with:
        changeMap: .github/clq/changemap.json
        mode: feature
    - name: Echo changelog values
      run: |
        echo "${name:?}"
        echo "${tag:?} -- ${status:?}"
        echo "${changes:?}"
      env:
        tag: ${{ steps.clq-validate.outputs.tag }}
        name: ${{ steps.clq-validate.outputs.name }}
        status: ${{ steps.clq-validate.outputs.status }}
        changes: ${{ steps.clq-validate.outputs.changes }}
  validate-release:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
    - name: Extract tag from the changelog
      uses: ./
      id: clq-extract
      with:
        changeMap: .github/clq/changemap.json
        mode: release
    - uses: denisa/semantic-tag-helper@v1
      with:
        mode: test
        tag: ${{ steps.clq-extract.outputs.tag }}
  tag:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ lint, test, validate-release ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      id: clq-extract
      with:
        changeMap: .github/clq/changemap.json
    - uses: denisa/semantic-tag-helper@v1
      with:
        mode: set
        tag: ${{ steps.clq-extract.outputs.tag }}
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.clq-extract.outputs.tag }}
        prerelease: ${{ steps.clq-extract.outputs.status == 'prereleased' }}
        name: ${{ steps.clq-extract.outputs.name }}
        body: ${{ steps.clq-extract.outputs.changes }}
