name: ci
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - run: make test
    - name: Validate the changelog
      uses: ./
      id: clq-validate
      with:
        changeMap: .github/clq/changemap.json
        mode: feature
    - name: Echo changelog values
      run: |
        echo "$release_name"
        echo "$release_tag -- $release_status"
        echo "$body"
      env:
        release_tag: ${{ steps.clq-validate.outputs.tag }}
        release_name: ${{ steps.clq-validate.outputs.name }}
        release_status: ${{ steps.clq-validate.outputs.status }}
        body: ${{ steps.clq-validate.outputs.changes }}
  validate-release:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - name: Extract tag from the changelog
      uses: ./
      id: clq-extract
      with:
        changeMap: .github/clq/changemap.json
        mode: release
    - name: Validate the tag has not yet been used
      env:
        TAG: ${{ steps.clq-extract.outputs.tag }}
      run: |
        if git ls-remote --exit-code --tags origin "refs/tags/$TAG" >/dev/null 2>&1; then
          echo "::error ::tag $TAG exists already"
          exit 1
        fi
  tag:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [ test, validate-release ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.2.0
    - uses: ./
      id: clq-extract
      with:
        changeMap: .github/clq/changemap.json
    - name: Create tags
      env:
        tag: ${{ steps.clq-extract.outputs.tag }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        version="${tag%%-*}"
        preversion="${tag##*-}"
        if [ "$version" != "$preversion" ]; then
          prefix="${version}-"
          tag="$preversion"
        fi

        tags=()
        before=''
        until [ "$before" = "$tag" ]; do
          tags+=("${prefix:-}${tag}")
          git tag "${tags[-1]}"
          before="$tag"
          tag="${tag%.*}"
        done

        # ensure this tag doesn't exist
        git push origin "${tags[0]}"
        # move all other tags
        git push origin --force "${tags[@]:1}"
    - uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ steps.clq-extract.outputs.tag }}
        prerelease: ${{ steps.clq-extract.outputs.status == 'prereleased' }}
        name: ${{ steps.clq-extract.outputs.name }}
        body: ${{ steps.clq-extract.outputs.changes }}
